fix(messenger-api): fix small

diff --git a/.github/workflows/ci-backend-for-all.yaml b/.github/workflows/ci-backend-for-all.yaml
--- a/.github/workflows/ci-backend-for-all.yaml
+++ b/.github/workflows/ci-backend-for-all.yaml
@@ -15,6 +15,7 @@ env:
   DB_PASSWORD: 12345678
   FIREBASE_AUTH_EMULATOR_HOST: 127.0.0.1:9099
   FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080
+  PUBSUB_EMULATOR_HOST: 127.0.0.1:8085
   GCP_SERVICE_KEY_JSON: ${{ secrets.STG_GCP_SA_KEY }}
 
 jobs:
@@ -74,7 +75,7 @@ jobs:
         done
         echo 'mysql is up - executing command'
 
-    - name: Wait start Firebase Authentication and Firestore
+    - name: Wait start Firebase emulators
       run: |
         #!/bin/bash
         retry=30
@@ -102,6 +103,18 @@ jobs:
           count=$(expr $count + 1)
         done
         echo 'firestore is up - executing command'
+
+        count=1
+        until curl ${PUBSUB_EMULATOR_HOST}; do
+          echo 'pubsub is unavailable - sleeping'
+          sleep 3
+          if [ $(expr $retry - $count) -le 0 ]; then
+            echo 'pubsub is unavailable - throw error for timeout'
+            exit 1
+          fi
+          count=$(expr $count + 1)
+        done
+        echo 'pubsub is up - executing command'
 
     ############################################
     # Setup project
